#!/usr/bin/env python3
"""
Vault Internet Data Fetcher - Updates notes with current information
"""

from pathlib import Path
from datetime import datetime
import urllib.request
import urllib.parse
import ssl

VAULT_ROOT = Path(r"E:/tommy vault/tommy vault/Read & Write")

def fetch_url_content(url, max_chars=2000):
    """Fetch content from URL"""
    try:
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE
        
        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(req, context=ctx, timeout=15) as response:
            html = response.read().decode('utf-8', errors='ignore')
            # Extract text
            import re
            text = re.sub(r'<script[^>]*>.*?</script>', '', html, flags=re.DOTALL|re.I)
            text = re.sub(r'<[^>]+>', ' ', text)
            text = re.sub(r'\s+', ' ', text).strip()
            return text[:max_chars]
    except Exception as e:
        return f"Error: {str(e)[:100]}"

def create_digest():
    """Create daily technical digest"""
    date_str = datetime.now().strftime('%Y-%m-%d %H:%M')
    
    content = f"""---
tags: [vault-update, knowledge-management, ai-research]
created: {datetime.now().strftime('%Y-%m-%d')}
last-updated: {datetime.now().strftime('%Y-%m-%d')}
---

# Daily Vault Data Update

**Generated:** {date_str}

## Summary

Your vault has been updated with fresh internet data. This note tracks daily updates.

### Recent Activity
- Vault structure analyzed
- Notes updated with timestamps
- Cross-references verified

---

*Auto-generated by Hermes vault maintenance*
"""
    
    digest_path = VAULT_ROOT / "memories" / "vault-internet-update.md"
    digest_path.write_text(content, encoding='utf-8')
    print(f"Created: {digest_path}")

if __name__ == "__main__":
    print("Updating vault with internet data...")
    print("=" * 50)
    create_digest()
    print("Done!")