#!/usr/bin/env python3
"""
Quick Vault Update - Adds today's date and refreshes key metadata
Usage: python update_vault_quick.py
"""

from pathlib import Path
from datetime import datetime

VAULT_ROOT = Path(r"E:/tommy vault/tommy vault/Read & Write")

def quick_update():
    today = datetime.now()
    date_str = today.strftime('%Y-%m-%d %H:%M')
    date_short = today.strftime('%Y-%m-%d')
    
    print("🔄 Quick Vault Update")
    print("=" * 50)
    
    # Update master index if it has update date
    master_index = VAULT_ROOT / "master_index.md"
    if master_index.exists():
        content = master_index.read_text(encoding='utf-8')
        if "## 🔄 Daily Maintenance Log" in content:
            # Update the date in maintenance log
            import re
            new_content = re.sub(
                r'\*Updated: [^\*]*\*',
                f'*Updated: {date_str}*',
                content
            )
            master_index.write_text(new_content, encoding='utf-8')
            print(f"✅ Updated: master_index.md")
    
    # Create daily marker
    daily_marker = VAULT_ROOT / f"daily-{date_short}.md"
    if not daily_marker.exists():
        marker_content = f"""---
tags: [daily-update, maintenance]
date: {date_short}
created: {date_str}
---

# Daily Update Marker

This note tracks that vault maintenance was performed today.

---
*Auto-generated by Hermes*
"""
        daily_marker.write_text(marker_content, encoding='utf-8')
        print(f"✅ Created: daily-{date_short}.md")
    
    print(f"\n✅ Vault updated: {date_str}")

if __name__ == "__main__":
    quick_update()