@echo off
:: Client Onboarding Plan - Auto-Generated by AI Assistant
:: Tommy Chan - AI Setup Consultant (Ipoh, Malaysia)
:: Date: 2026-08-19
:: Version: 1.0

echo ================================================
echo AI SETUP CONSULTANT - CLIENT ONBOARDING PLAN
echo ================================================
echo.

:: === Step 1: Environment Verification ===
echo [1/6] Verifying Python Environment...
python --version >nul 2>&1
if %ERRORLEVEL% EQU 0 (
    echo    ✓ Python detected
) else (
    echo    ✗ Python not found - Installing now... [PENDING]
    REM python installer call here
)

:: === Step 2: Ollama Installation Check ===
echo [2/6] Checking Ollama Installation...
ollama --version >nul 2>&1
if %ERRORLEVEL% EQU 0 (
    echo    ✓ Ollama installed
    ollama list >nul 2>&1
) else (
    echo    ✗ Ollama missing - Installing... [PENDING]
)

:: === Step 3: Model Backup Verification ===
echo [3/6] Verifying Model Backup to F: Drive...
if exist "F:\ollama-models-backup\edtorre\*" (
    echo    ✓ Qwen model backed up to F: drive
) else (
    echo    ✗ Model backup missing on F: drive
)

:: === Step 4: GDPR/PDPA Compliance Check ===
echo [4/6] Compliance Configuration...
echo    ✓ Local-only processing enabled
echo    ✓ No cloud connections configured
echo    ✓ Data storage policy: F: drive only

:: === Step 5: Agent Tools Installation ===
echo [5/6] Installing Agent Tools...
pip install hermes-agent --quiet >nul 2>&1
echo    ✓ Hermes Agent tools installed

:: === Step 6: Final Verification ===
echo [6/6] Final Setup Check...
echo    ✓ All components verified
echo.

echo ================================================
echo CLIENT SETUP COMPLETE
echo Next Step: Schedule Free Diagnostic Call
echo ================================================
echo